In [14]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

# Generating Data

In [15]:
X = np.array([3.77, 2.47, 2.19, 0.21, 1.63, 1.69, 5.09, 4.23, 5.02, 4.41, 4.729, 6.01]).reshape(-1,1)
y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

# X is the size of tumor.

# y is 0 or 1.
# 0 means no cancer
# 1 means cancer

In [16]:
X

array([[3.77 ],
       [2.47 ],
       [2.19 ],
       [0.21 ],
       [1.63 ],
       [1.69 ],
       [5.09 ],
       [4.23 ],
       [5.02 ],
       [4.41 ],
       [4.729],
       [6.01 ]])

# Training

In [17]:
log_reg = LogisticRegression()
LR = log_reg.fit(X,y)

# Get Prediction from unseen value

In [18]:
X_test = np.array([3.50]).reshape(-1,1)

# Getting Probabilities of prediction

In [19]:
LR.predict_proba(X_test)

array([[0.54113245, 0.45886755]])

# Getting  class prediction

In [ ]:
y_pred = LR.predict(X_test)

In [ ]:
y_pred

array([0])

# Applying Naive Bayes Classifier

In [20]:
NB_model = GaussianNB()

In [21]:
NB_model.fit(X,y)

GaussianNB()

# Testing Naive Bayes Classifier

In [22]:
X_test = np.array([3.50]).reshape(-1,1)

In [23]:
NB_model.predict_proba(X_test)

array([[0.80088133, 0.19911867]])

In [24]:
y_pred_NB =NB_model.predict(X_test)

In [25]:
y_pred_NB

array([0])